
import { GoogleGenAI, Modality } from "@google/genai";
import { ImageState } from '../types';

export const generateTryOnImage = async (
  modelImage: ImageState,
  productImage: ImageState
): Promise<string> => {
  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const modelImagePart = {
      inlineData: {
        data: modelImage.base64,
        mimeType: modelImage.mimeType,
      },
    };

    const productImagePart = {
      inlineData: {
        data: productImage.base64,
        mimeType: productImage.mimeType,
      },
    };

    const textPart = {
      text: "You are a virtual fashion assistant. Your task is to realistically place the clothing item from the second image onto the person in the first image. Ensure the fit, drape, and lighting look natural. The first image is the model, and the second image is the clothing item. Return only the final image.",
    };

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [modelImagePart, productImagePart, textPart],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        return part.inlineData.data;
      }
    }
    
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Error generating try-on image:", error);
    throw new Error("Failed to generate image. Please check the console for more details.");
  }
};
